### ISSUE TITLE
Highlighting for EPP

### ISSUE THREAD

**Issue by hb0nes** [amaanq/tree-sitter-puppet#8]
Puppet (or epuppet) templates are an integral part of Puppet.
I don't get any highlighting in .epp files, am I doing something wrong or is this not supported by this integration?

**Comment by amaanq** [comment]
embedded languages are always a pain point since the inner embedded highlight is done by determining the extension. This would be best written in your own config or as a standalone plugin, to register the epp filetype as epuppet, take the embedded template parser and parse that code, then inject puppet into code regions. It's out of the scope of the grammar though, so I'll close this out

**Comment by hb0nes** [comment]
> embedded languages are always a pain point since the inner embedded highlight is done by determining the extension. This would be best written in your own config or as a standalone plugin, to register the epp filetype as epuppet, take the embedded template parser and parse that code, then inject puppet into code regions. It's out of the scope of the grammar though, so I'll close this out

I understand from your reaction that it is not straightforward for me to set this up?  
I have no experience writing plugins, unfortunately.

_btw epp is already registered as epuppet (checked `:set ft?`)_
